version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo
    ports:
      - "2181:2181"
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo:2888:3888 server.2=zoo1:2888:3888 server.3=zoo2:2888:3888
    networks:
      kafka-zoo-net:
        ipv4_address: 172.19.0.2

  zookeeper1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2185:2185"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo:2888:3888 server.2=zoo1:2888:3888 server.3=zoo2:2888:3888
    container_name: zookeeper1
    networks:
      kafka-zoo-net:
        ipv4_address: 172.19.0.3

  zookeeper2:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo2
    ports:
      - "2186:2186"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo:2888:3888 server.2=zoo1:2888:3888 server.3=zoo2:2888:3888
    container_name: zookeeper2
    networks:
      kafka-zoo-net:
        ipv4_address: 172.19.0.4

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
      - zookeeper1
      - zookeeper2
    container_name: kafka
    networks:
      kafka-zoo-net:
        ipv4_address: 172.19.0.5

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9093
    depends_on:
      - zookeeper
      - zookeeper1
      - zookeeper2
    container_name: kafka1
    networks:
      kafka-zoo-net:
        ipv4_address: 172.19.0.6

networks:
  kafka-zoo-net:
    external:
      name: kafka-zoo-net
